/* tslint:disable */
/* eslint-disable */
/**
 * HelixHub - API
 * This is the API for the HelixHub API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddUserDto
 */
export interface AddUserDto {
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof AddUserDto
     */
    group: number;
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    password: string;
}
