/* tslint:disable */
/* eslint-disable */
/**
 * HelixHub - API
 * This is the API for the HelixHub API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PermissionDto } from './permission-dto';
/**
 * 
 * @export
 * @interface GroupPermissionDto
 */
export interface GroupPermissionDto {
    /**
     * The unique ID of the group associated with the permission.
     * @type {string}
     * @memberof GroupPermissionDto
     */
    groupId: string;
    /**
     * The unique ID of the permission associated with the group.
     * @type {string}
     * @memberof GroupPermissionDto
     */
    permissionId: string;
    /**
     * The permission information associated with the group.
     * @type {PermissionDto}
     * @memberof GroupPermissionDto
     */
    permission: PermissionDto;
}
