/* tslint:disable */
/* eslint-disable */
/**
 * HelixHub - API
 * This is the API for the HelixHub API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupPermissionDto } from './group-permission-dto';
/**
 * 
 * @export
 * @interface GroupDto
 */
export interface GroupDto {
    /**
     * The unique ID of the group.
     * @type {number}
     * @memberof GroupDto
     */
    id: number;
    /**
     * The name of the group.
     * @type {string}
     * @memberof GroupDto
     */
    name: string;
    /**
     * The permissions associated with the group.
     * @type {Array<GroupPermissionDto>}
     * @memberof GroupDto
     */
    groupPermission: Array<GroupPermissionDto>;
}
