/* tslint:disable */
/* eslint-disable */
/**
 * HelixHub - API
 * This is the API for the HelixHub API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PermissionDto
 */
export interface PermissionDto {
    /**
     * The unique ID of the permission.
     * @type {string}
     * @memberof PermissionDto
     */
    id: string;
    /**
     * The optional description of the permission.
     * @type {string}
     * @memberof PermissionDto
     */
    description?: string;
}
