/* tslint:disable */
/* eslint-disable */
/**
 * HelixHub - API
 * This is the API for the HelixHub API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupDto } from './group-dto';
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * Die eindeutige ID des Benutzers.
     * @type {number}
     * @memberof UserDto
     */
    id: number;
    /**
     * Die optionale ID der Gruppe, zu der der Benutzer gehört.
     * @type {string}
     * @memberof UserDto
     */
    groupId?: string;
    /**
     * Die Gruppeninformationen des Benutzers.
     * @type {GroupDto}
     * @memberof UserDto
     */
    group?: GroupDto;
    /**
     * Der Name des Benutzers.
     * @type {string}
     * @memberof UserDto
     */
    name: string;
    /**
     * Die E-Mail-Adresse des Benutzers.
     * @type {string}
     * @memberof UserDto
     */
    email: string;
    /**
     * Das Erstellungsdatum des Benutzerkontos.
     * @type {Date}
     * @memberof UserDto
     */
    created: Date;
}
